# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
<<<<<<< HEAD

  # username: root
  # password:



=======
  # username: root
  # password:
  # username: jeska
  # password: jeska 
>>>>>>> 57f1fc221548080fdd8e7ff179d6c8f3c4a61015
  # socket: /tmp/mysql.sock 

  
  



  # Mutaga's credentials
  username: tasha
  host: 127.0.0.1
  # socket: /tmp/mysql.sock
<<<<<<< HEAD
  # password: tashexc2754

  username: frank
  host: 127.0.0.1
  password: Francis@1234
  socket: /var/run/mysqld/mysqld.sock



=======
  password: tashexc2754
>>>>>>> 57f1fc221548080fdd8e7ff179d6c8f3c4a61015
development:
  <<: *default
  host: 127.0.0.1 
  database: ticketing_rails

production:
  <<: *default
  database: api_eventful_production
  username: api_eventful
  password: <%= ENV["API_EVENTFUL_DATABASE_PASSWORD"] %>

